name: kumaconda
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.10.0=py37_0
  - aiohttp=3.6.2=py37h7b6447c_0
  - albumentations=0.4.6=py_0
  - argon2-cffi=20.1.0=py37h8f50634_1
  - astor=0.8.1=py37_0
  - async-timeout=3.0.1=py37_0
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - autopep8=1.5.4=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - catboost=0.24=py37hc8dfbb8_0
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1.1=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37h8f50634_0
  - dask-core=2.30.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - efficientnet-pytorch=0.7.0=pyh9f0ad1d_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.10.2=h5ab3b9f_0
  - gast=0.2.2=py37_0
  - gdcm=2.8.9=py37h71b2a6d_0
  - geos=3.8.1=he1b5a44_0
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.22.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=he1b5a44_1001
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imgaug=0.4.0=py_1
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=5.8.0=py37_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=5.2.0=py37_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=he1b5a44_1001
  - libjpeg-turbo=2.0.5=h516909a_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0=hd408876_0
  - libsodium=1.0.18=h516909a_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lightgbm=2.3.0=py37he6710b0_0
  - llvmlite=0.34.0=py37h269e1b5_4
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3=py37_0
  - markupsafe=1.1.1=py37hb5d75c8_2
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - matplotlib-venn=0.11.6=pyh9f0ad1d_0
  - mistune=0.8.4=py37h8f50634_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.6=py37h7b6447c_1
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py37hc8dfbb8_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - networkx=2.5=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - notebook=6.1.4=py37hc8dfbb8_0
  - numba=0.51.2=py37h04863e7_1
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1h=h516909a_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py37he6710b0_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - patsy=0.5.1=py37_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.2.3=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - protobuf=3.13.0=py37hf484d3e_1
  - ptyprocess=0.6.0=py_1001
  - py-opencv=3.4.2=py37hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=py_2
  - pydicom=2.0.0=pyh9f0ad1d_0
  - pygments=2.7.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h8f50634_1
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h161383b_2
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.2=py37hac76be4_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - shapely=1.7.1=py37hedb1597_0
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.0=py37h7b6447c_0
  - tbb=2020.3=hfd86e86_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=gpu_py37h7a4bb67_0
  - tensorflow-base=2.1.0=gpu_py37h6c5654b_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.9.1=py37hc8dfbb8_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.11.1=py_0
  - torchvision=0.7.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.50.2=pyh9f0ad1d_0
  - traitlets=5.0.4=py_1
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - wrapt=1.12.1=py37h7b6447c_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.0=py37h7b6447c_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
